//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PC_TrackEntities : DbContext
    {
        public PC_TrackEntities()
            : base("name=PC_TrackEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Applications> Applications { get; set; }
        public virtual DbSet<Installedapp> Installedapp { get; set; }
        public virtual DbSet<PC> PC { get; set; }
        public virtual DbSet<Used_app> Used_app { get; set; }
        public virtual DbSet<Worked_time> Worked_time { get; set; }
    }
}
