//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worked_time
    {
        public int PC_ID { get; set; }
        public string Time { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual PC PC { get; set; }
    }
}
